services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=life_stats
    ports:
      - '5432:5432'
    volumes:
      - life_stats_db:/var/lib/postgresql/data

  dbgate:
    build: docker
    image: dbgate/dbgate:alpine
    ports:
      - 3100:3000

volumes:
  life_stats_db:
