services:
    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=workout_tracker
        ports:
            - '5432:5432'
        volumes:
            - workout_tracker_db:/var/lib/postgresql/data

    dbgate:
        build: docker
        image: dbgate/dbgate:alpine
        ports:
            - 3100:3000

volumes:
    workout_tracker_db:
