packages:
  - 'packages/*'
  - 'libs/db'
  - 'libs/config'
  - 'libs/read-market'
  - 'libs/shared-types'
  - 'apps/*'
  - 'libs/notify'
  - 'libs/notify-scouts'
  - 'libs/logger'
  - 'libs/ui'
  - 'libs/eslint-config'
  - 'libs/typescript-config'
  - 'libs/time'
syncInjectedDepsAfterScripts:
  - 'build'
injectWorkspacePackages: true
